### ISSUE TITLE
No video and audio: Ignoring empty DtlsFingerprint extension

### ISSUE THREAD

**Issue by zsinba** [avstack/gst-meet#31] opened 2021-12-24 14:02 UTC
![image](https://user-images.githubusercontent.com/890157/147357731-a9018c5e-5c5f-42b0-be33-153ae2786c37.png)

jvb log:
Ignoring empty DtlsFingerprint extension: <transport xmlns='urn:xmpp:jingle:transports:ice-udp:1'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' required='false'/></transport>

Same error when using Docker gst-meet.
Probably not WSS or WS. Looks like stun or turn didn't work;
My Jitsi is not a Docker version, it is a properly installed version and it works fine.

**Comment by jbg** [comment] 2021-12-24 14:12
`Ignoring empty DtlsFingerprint extension` is not related to the lack of audio/video.

The error in your image was already reported by you in a separate issue, and is a duplicate of #2.

Please stop opening frivolous issues, we do not have time to triage vague and badly-reported issues.

**Closed by jbg** 2021-12-24 14:12 UTC
