### ISSUE TITLE
docker could not get correct result

### ISSUE THREAD

**Issue by zsinba** [avstack/gst-meet#28] opened 2021-12-23 16:40 UTC
Compile the docker and run it on ubuntu 20.04;

root@ubuntu:~# docker logs beautiful_rhodes 
2021-12-23T16:34:07.239624Z  INFO Connecting XMPP WebSocket to wss://m.xxxxxxxxx.com/xmpp-websocket
2021-12-23T16:34:07.879625Z  INFO Connected XMPP WebSocket
2021-12-23T16:34:07.928789Z  INFO Logged in anonymously
2021-12-23T16:34:07.954366Z  INFO My JID: pmnzz4k11c81igx9@m.xxxxxxxxx.com/uGaZr7GH
2021-12-23T16:34:08.002334Z  WARN discovering external services failed: STUN/TURN will not work
2021-12-23T16:35:08.185164Z ERROR fatal (in read loop): WebSocket protocol error: Connection reset without closing handshake

Caused by:
    Connection reset without closing handshake
2021-12-23T16:38:15.651776Z  INFO Connecting XMPP WebSocket to wss://m.xxxxxxxxx.com/xmpp-websocket
2021-12-23T16:38:15.974019Z  INFO Connected XMPP WebSocket
2021-12-23T16:38:16.028983Z  INFO Logged in anonymously
2021-12-23T16:38:16.056449Z  INFO My JID: sezc6qdgz-q-tra6@m.xxxxxxxxx.com/iwrM1M1g
2021-12-23T16:38:16.112016Z  WARN discovering external services failed: STUN/TURN will not work

**Comment by jbg** [comment] 2021-12-23 16:42
```
2021-12-23T16:35:08.185164Z ERROR fatal (in read loop): WebSocket protocol error: Connection reset without closing handshake
```

The XMPP server closed the WebSocket connection, please check your XMPP server's logs to see why.

**Comment by zsinba** [comment] 2021-12-23 16:58
Not for this reason. Make sure WSS is normal
The connection did not respond for a period of time, and then it was closed.

**Comment by zsinba** [comment] 2021-12-23 17:00
![image](https://user-images.githubusercontent.com/890157/147271209-625bca66-b80b-424f-8037-721a29a3a407.png)

**Comment by jbg** [comment] 2021-12-23 17:09
Duplicate of #2

**Closed by jbg** 2021-12-23 17:09 UTC

**Comment by zsinba** [comment] 2021-12-23 17:29
I think they should not be the same problem. 
Even if there is no interruption of 2 minutes. It also failed to display the image normally.

**Comment by jbg** [comment] 2021-12-23 17:30
Then I think you have two problems, and the issue of not displaying the video is most likely unrelated to the XMPP WebSocket closing.

**Comment by zsinba** [comment] 2021-12-23 17:33
I think so.

**Comment by jbg** [comment] 2021-12-23 17:34
Please share the `gst-meet` invocation including full pipelines. Most likely the video is not displaying due to a pipeline issue. Note that extra setup is probably required for video sinks when running inside Docker (like forwarding X11 sockets / similar for other platforms).

**Comment by zsinba** [comment] 2021-12-23 17:39
![image](https://user-images.githubusercontent.com/890157/147274910-ff1a2cc2-7747-43aa-8bcb-d750ad411013.png)

pls talk about it with #29
